name: Release

on:
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set manifest version number
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          python3 -c "
          import json, os
          version = os.environ['VERSION'].lstrip('v')
          with open('custom_components/solidgps/manifest.json', 'r') as f:
              manifest = json.load(f)
          manifest['version'] = version
          with open('custom_components/solidgps/manifest.json', 'w') as f:
              json.dump(manifest, f, indent=2)
              f.write('\n')
          "

      - name: Create zip
        run: |
          cd custom_components/solidgps
          zip solidgps.zip -r ./ --exclude='*__pycache__*'

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./custom_components/solidgps/solidgps.zip
          asset_name: solidgps.zip
          tag: ${{ github.ref }}
          overwrite: true
